name: Package

on:
  release:
    types: [published]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true

jobs:
  package-chrome-extension:
    name: Package Chrome Extension
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.release.tag_name, 'chrome-extension-')}}
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - run: npm ci

      - run: npx nx run-many --target=build --project=chrome-extension

      - name: Attach artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/apps/zip/*.zip'
          file_glob: true
          overwrite: true
          tag: ${{ github.event.release.tag_name || inputs.tag }}
